#??????
spring.datasource.url=jdbc:mysql://localhost:3306/ershou?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.continue-on-error=false
spring.datasource.test-while-idle=true
#??????????????
spring.datasource.test-on-borrow=false
#?????????????????
spring.datasource.test-on-return=false
spring.datasource.validation-query=SELECT 1 FROM DUAL
#?????????????test-while-idle???????5??
spring.datasource.time-between-eviction-runs-millis=300000
#???????????? ???30??
spring.datasource.min-evictable-idle-time-millis=1800000
spring.datasource.initial-size=5
#??????????????.
spring.datasource.max-active=50
#???????????????????????.
spring.datasource.max-wait=60000
#????????????
spring.datasource.min-idle=5

spring.jpa.database=MYSQL
#??????sql??????
spring.jpa.show-sql=true
# ???????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#?????
spring.devtools.restart.enabled=true
#??????
ylrc.upload.photo.sufix=.jpg,.png,.gif,.jpeg
ylrc.upload.photo.maxsize=1024
ylrc.upload.photo.path=
#???????
ylrc.database.backup.dir=
ylrc.database.backup.username=root
ylrc.database.backup.password=123456
ylrc.database.backup.database.name=db_boot_base
