########################################################
########################################################
server.port=8080
server.servlet.session.timeout=1800
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#?????????
spring.profiles.active=dev
###FREEMARKER
#??????HttpServletRequest?????????????????????
spring.freemarker.allow-request-override=false
spring.freemarker.cache=false
spring.freemarker.check-template-location=true
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
#???????????????????????????
spring.freemarker.expose-request-attributes=false
#??????HttpSession?????????????????????
spring.freemarker.expose-session-attributes=false
#?????????Spring macro RequestContext??RequestContext?Spring?????.
spring.freemarker.expose-spring-macro-helpers=false
spring.freemarker.prefix=
#spring.freemarker.request-context-attribute=
#spring.freemarker.settings.
spring.freemarker.settings.template_update_delay=0
spring.freemarker.settings.default_encoding=UTF-8
spring.freemarker.suffix=.ftl
spring.freemarker.template-loader-path=classpath:/templates/
#spring.freemarker.view-names= # whitelist of view names that can be resolved
spring.freemarker.settings.number_format=0.##
spring.servlet.multipart.maxFileSize=2MB

